CREATE DATABASE IF NOT EXIST Clinic;

CREATE TABLE IF NOT EXISTS patients (
	ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(50),
	DATE_OF_BIRTH DATE,
	PRIMARY KEY(ID)
)

CREATE TABLE IF NOT EXISTS medical_histories (
	ID INT GENERATED ALWAYS AS IDENTITY,
	admitted_at timestamp,
	status VARCHAR(150),
	patient_id INT REFERENCES patients(id),
	PRIMARY KEY(ID)
)

CREATE TABLE IF NOT EXISTS treatments (
	ID INT GENERATED ALWAYS AS IDENTITY,
	type VARCHAR(20),
	name VARCHAR(50),
	PRIMARY KEY(ID)
)
